name: rubyspec C-API extensions

inputs:
  builddir:
    required: false
    default: '.'
  make:
    required: false
    default: 'make -s'

outputs:
  key:
    value: >-
      ${{
      !steps.restore.outputs.cache-hit &&
      github.ref == 'refs/heads/master' &&
      steps.config.outputs.key
      }}

runs:
  using: composite

  steps:
    - id: config
      shell: bash
      run: |
        eval $(grep -e '^arch *=' -e '^ruby_version *=' -e '^DLEXT *=' Makefile |
            sed 's/ *= */=/')
        key=capiexts-${arch}-${ruby_version}
        echo key=$key >> $GITHUB_OUTPUT
        echo DLEXT=$DLEXT >> $GITHUB_OUTPUT
      working-directory: ${{ inputs.builddir }}

    - name: CAPI extensions cache
      uses: actions/cache@0400d5f644dc74513175e3cd8d07132dd4860809 # v4.2.4
      id: cache
      with:
        path: ${{ inputs.builddir }}/spec/ruby/optional/capi/ext/
        key: ${{ steps.config.outputs.key }}

    - name: Run test-spec with previous CAPI extension binaries
      shell: bash
      run: |
        touch spec/ruby/optional/capi/ext/*.$DLEXT
        [ ! -f spec/ruby/optional/capi/ext/\*.$DLEXT ]
        ${{ inputs.make }} SPECOPTS=optional/capi test-spec
      env:
        DLEXT: ${{ steps.config.outputs.DLEXT }}
      working-directory: ${{ inputs.builddir }}
      if: ${{ steps.cache.outputs.cache-hit }}
